apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: flexcub-testing
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ajiqbrainx/backend:2
          ports:
            - containerPort: 8080


           
            
            
