server:
  servlet:
    context-path: /resource-planning
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:postgresql://34.127.25.181:5432/QA
    username: flexcubdev
    password: flexcubdev
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.zeptomail.com
    port: 465
    username: emailapikey
    password: wSsVR610+xamXK90mGGpde08y1gBA1uiEkko2FD37XT7SPGU9Mc5wxfHVwKhT/RKFTJoRzURpb0gzk0C1TUIitUtnlgDCCiF9mqRe1U4J3x17qnvhDzPWW5VlRGLJYgIxAhtmWFnEsgh+g==
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
          auth: true
          starttls:
            enable: true
flexcub:
  baseurl: https://qa.flexcub.com/activation
  baseurlOwner: https://qa.flexcub.com/activation/skillowner
  baseURLforgotPassword: https://qa.flexcub.com/forgot-password
  baseURLHiringProcess: https://qa.flexcub.com/sodashboard
  baseURLRejectionMail: https://qa.flexcub.com/sodashboard
  baseURLScheduleMail: https://qa.flexcub.com/sodashboard
  baseURLSelectedForRoundMail: https://qa.flexcub.com/sodashboard
  baseURLNewSlotRequest: https://qa.flexcub.com/sodashboard
  baseURLAccountExpiry: https://dev.flexcub.com/sodashboard
  downloadURLOwnerResume: https://qa.flexcub.com/resource-planning/api/v1/fileDownloadResume?id=
  downloadURLOwnerImage: https://qa.flexcub.com/resource-planning/api/v1/fileDownloadImage?id=
  downloadURLOwnerOtherDocument: https://qa.flexcub.com/resource-planning/api/v1/otherFilesDownload?ownerId=
  downloadURLOwnerFederal: https://qa.flexcub.com/resource-planning/api/v1/fileDownloadFederal?id=
  downloadURLMSA: https://qa.flexcub.com/resource-planning/v1/skillSeekerMSAController/downloadOwnerAgreement?id=
  downloadURLSOW: https://qa.flexcub.com/resource-planning/v1/statementOfWorkController/downloadOwnerAgreementForSow?id=
  downloadURLPO: https://qa.flexcub.com/resource-planning/v1/purchaseOrder/downloadOwnerAgreementPO?id=
  downloadURLTS: https://qa.flexcub.com/resource-planning/v1/OwnerSkillTimeSheet/downloadTimesheetDocuments?id=
  from:
    email: no-reply@flexcub.com
  defaultTemplateName: QbrainxSample_template_Final.xlsx
  emailRegex: "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$"
springdoc:
  group-configs:
    - group: com.flexcub
      packagesToScan:
        - "com.flexcub.resourceplanning"
  swagger-ui:
    path: /resource-planning-swagger-ui.html
  api-docs:
    path: /v3/resource-planning-api-docs
  liquibase:
    enabled: true

