server:
  servlet:
    context-path: /resource-planning
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:postgresql://34.127.25.181/Development #Change it as per your local Database name
    username: flexcubdev #Change it as per your local username
    password: flexcubdev #Change it as per your local password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.zeptomail.com
    port: 465
    username: emailapikey
    password: wSsVR610+xamXK90mGGpde08y1gBA1uiEkko2FD37XT7SPGU9Mc5wxfHVwKhT/RKFTJoRzURpb0gzk0C1TUIitUtnlgDCCiF9mqRe1U4J3x17qnvhDzPWW5VlRGLJYgIxAhtmWFnEsgh+g==
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
          auth: true
          starttls:
            enable: true

flexcub:
  baseurl: https://dev.flexcub.com/activation
  baseurlOwner: https://dev.flexcub.com/activation/skillowner
  baseURLforgotPassword: https://dev.flexcub.com/forgot-password
  baseURLHiringProcess: https://dev.flexcub.com/sodashboard
  baseURLRejectionMail: https://dev.flexcub.com/sodashboard
  baseURLScheduleMail: https://dev.flexcub.com/sodashboard
  baseURLSelectedForRoundMail: https://dev.flexcub.com/sodashboard
  baseURLNewSlotRequest: https://dev.flexcub.com/sodashboard
  baseURLSkillOwnerTimeSheet: https://dev.flexcub.com/sodashboard
  baseURLAccountExpiry: https://dev.flexcub.com/sodashboard
  downloadURLOwnerResume: http://localhost:8080/resource-planning/api/v1/fileDownloadResume?id= #Change it as your localhost: Port
  downloadURLOwnerImage: http://localhost:8080/resource-planning/api/v1/fileDownloadImage?id=  #Change it as your localhost: Port
  downloadURLOwnerOtherDocument: http://localhost:8080/resource-planning/api/v1/otherFilesDownload?ownerId=  #Change it as your localhost: Port
  downloadURLOwnerFederal: http://localhost:8080/resource-planning/api/v1/fileDownloadFederal?id=
  downloadURLMSA: http://localhost:8080/resource-planning/v1/skillSeekerMSAController/downloadOwnerAgreement?id=
  downloadURLSOW: http://localhost:8080/resource-planning/v1/statementOfWorkController/downloadOwnerAgreementForSow?id=
  downloadURLPO: http://localhost:8080/resource-planning/v1/purchaseOrder/downloadOwnerAgreementPO?id=
  downloadURLTS: http://localhost:8080/resource-planning/v1/OwnerSkillTimeSheet/downloadTimesheetDocuments?id=
  from:
    email: flexcubjunior@gmail.com
  defaultTemplateName: QbrainxSample_template_Final.xlsx
  emailRegex: "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$"

springdoc:
  group-configs:
    - group: com.flexcub
      packagesToScan:
        - "com.flexcub.resourceplanning"
  swagger-ui:
    path: /resource-planning-swagger-ui.html
  api-docs:
    path: /v3/resource-planning-api-docs
  liquibase:
    enabled: true